### ISSUE TITLE
No matching template for flow id 258

### ISSUE THREAD

**Issue by iJanki** [logstash-plugins/logstash-codec-netflow#75]
I'm using version 3.4.0

I've seen this reported before but together with other issues. I just get the following warnings:

```
[2017-03-17T11:43:47,681][WARN ][logstash.codecs.netflow  ] No matching template for flow id 258
[2017-03-17T11:43:47,682][WARN ][logstash.codecs.netflow  ] No matching template for flow id 262
[2017-03-17T11:43:47,683][WARN ][logstash.codecs.netflow  ] No matching template for flow id 258
[2017-03-17T11:43:47,683][WARN ][logstash.codecs.netflow  ] No matching template for flow id 262
[2017-03-17T11:43:47,684][WARN ][logstash.codecs.netflow  ] No matching template for flow id 260
[2017-03-17T11:43:47,685][WARN ][logstash.codecs.netflow  ] No matching template for flow id 258
[2017-03-17T11:43:47,685][WARN ][logstash.codecs.netflow  ] No matching template for flow id 266
[2017-03-17T11:43:47,686][WARN ][logstash.codecs.netflow  ] No matching template for flow id 258
[2017-03-17T11:43:47,687][WARN ][logstash.codecs.netflow  ] No matching template for flow id 262
[2017-03-17T11:43:47,688][WARN ][logstash.codecs.netflow  ] No matching template for flow id 262
[2017-03-17T11:43:47,688][WARN ][logstash.codecs.netflow  ] No matching template for flow id 258
[2017-03-17T11:43:47,690][WARN ][logstash.codecs.netflow  ] No matching template for flow id 258
[2017-03-17T11:43:47,690][WARN ][logstash.codecs.netflow  ] No matching template for flow id 262
[2017-03-17T11:43:47,691][WARN ][logstash.codecs.netflow  ] No matching template for flow id 262
[2017-03-17T11:43:47,692][WARN ][logstash.codecs.netflow  ] No matching template for flow id 258
[2017-03-17T11:43:47,692][WARN ][logstash.codecs.netflow  ] No matching template for flow id 258
[2017-03-17T11:43:47,694][WARN ][logstash.codecs.netflow  ] No matching template for flow id 258
[2017-03-17T11:43:47,694][WARN ][logstash.codecs.netflow  ] No matching template for flow id 262
[2017-03-17T11:43:47,695][WARN ][logstash.codecs.netflow  ] No matching template for flow id 262
```

I'm not sure what it means. The entries that get accepted look like this, they all have flowset_id = 260:

```
"netflow" => {
                   "dst_as" => 0,
        "forwarding_status" => {
            "reason" => 0,
            "status" => 1
        },
                  "in_pkts" => 1,
           "first_switched" => "2017-03-17T11:42:43.999Z",
               "flowset_id" => 260,
              "l4_src_port" => 52119,
                 "in_bytes" => 42,
                 "protocol" => 6,
                "tcp_flags" => 16,
             "ingressVRFID" => 1610612736,
              "l4_dst_port" => 443,
                   "src_as" => 0,
                "direction" => 1,
              "output_snmp" => 451,
                 "dst_mask" => 18,
            "ipv4_dst_addr" => "xxxxxxx",
                  "src_tos" => 0,
                 "src_mask" => 22,
                  "version" => 9,
             "flow_seq_num" => 2987128253,
            "ipv4_src_addr" => "xxxxxxx",
              "egressVRFID" => 1610612736,
               "input_snmp" => 165,
            "last_switched" => "2017-03-17T11:42:43.999Z",
          "flow_sampler_id" => 1,
        "bgp_ipv4_next_hop" => "xxxxxxx"
```

**Comment by ajrgrubbs** [comment]
So I believe that the way Netflow works is it should send out "templates" as part of the flow at some regular interval. They tell the Netflow consumer (aka this codec plugin) how to read other incoming data. For the Netflow I personally use, this "update" appears to happen once every 20 minutes or so. After the update happens the messages go away. Try letting it run for a while and see what happens.

Keep in mind that by default these "templates" are held in memory, and lost when logstash stops. There is a configuration option for the codec called `netflow_definitions`, which accepts a filesystem path. When provided, it saves the templates in a file which it reads from at boot. This was broken in recent versions but should be fixed in 3.4.0. I'd recommend checking that out.

Hopefully this addresses your issues.

**Comment by iJanki** [comment]
Thanks for the reply, I don't know much about netflow. 
However we kept it running for several hours and the issue has not fixed.
The netflow data is actually coming from a different sources, and not having the source IP available to the codec makes it hard to debug which devices are failing sending templates.

I'm using the cache file as well. No trace of the missing IDs after a couple of hours.

**Comment by ajrgrubbs** [comment]
Gotcha. Also not a Netflow expert here - so at this point I don't have much better suggestions than to check out what more logging can tell you. You can [enable debug logging](https://www.elastic.co/guide/en/logstash/current/logging.html#_logging_apis) on the plugin. In the past when dealing with my own (self-inflicted) bugs I've also found it handy to just go directly into the plugin's source and make it output what I need. [This commented out line](https://github.com/logstash-plugins/logstash-codec-netflow/blob/master/lib/logstash/codecs/netflow.rb#L324) might be handy if you're trying to identify a specific source.

Good luck!

**Comment by iJanki** [comment]
Thanks, we hacked udp input plugin to pass metadata info, so we got the source IPs at least for now...

**Comment by jorritfolmer** [comment]
Did the metadata hack in the udp input fix things?

**Comment by iJanki** [comment]
No it didn't fix the problem. Then we stopped using this plugin as it wasn't performant enough as a nprobe collector cause it processes 1 event at a time. The udp socket was losing packets heavily for our kind of traffic.

**Comment by jorritfolmer** [comment]
Yes plus there seem to be a multithreading issue, see #53.
If I only had time :)

**Comment by jorritfolmer** [comment]
I've been doing some performance testing on the netflow codec lately, and decoding tops at around 3000 flows per second with 2 UDP workers and 2 CPU's, with 0 loss.

Exporting more than 3000 flows per second to this setup results in losses at the udp socket.
Although increasing the `queue_size` at the udp plugin does help smooth losses by queueing more.

Even though you switched collectors, can you share some numbers about your environment, e.g in terms of (avg|max) flows per second you're collecting? This gives us something to aim for 💪

**Comment by iJanki** [comment]
In our case we need to process more than 30000 flows per seconds, I'm not sure if that could be useful.

**Comment by jorritfolmer** [comment]
It seems possible to get to 15000 flows/sec on a 16 core machine, see thread #85.
What collector are you currently using btw, and can you comment its performance?
